spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:exam_system}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

# AES 加密密钥配置
aes:
  secret: ${AES_SECRET:LM48/vNKyOLISngwkqDI4aSAyVT5DJ7lohtMJqWOqvpojDfkaLnE1v822rLgENp3eeuMagJCtP6voBtgBroKdQ==}

logging:
  level:
    com.southcollege.exam: debug
    org.springframework.jdbc: debug
